DWAPlannerROS:

### Parâmetros de configuração do robô

  acc_lim_x : 2.5
  # O limite de aceleração x do robô em metros/seg^2

  acc_lim_y : 2.5
  # O limite de aceleração y do robô em metros/seg^2

  acc_lim_theta : 3
  # O limite de aceleração rotacional do robô em radianos/s^2 

  max_trans_vel : 0.8
  # O valor absoluto da velocidade de translação máxima para o robô em m/s 

  min_trans_vel : 0.1
  # O valor absoluto da velocidade translacional mínima para o robô em m/s

  max_vel_x : 0.8
  # A velocidade máxima x para o robô em m/s.

  min_vel_x : -0.8
  # A velocidade x mínima para o robô em m/s, negativa para o movimento para trás.

  max_vel_y : 0
  # A velocidade y máxima para o robô em m/s

  min_vel_y : 0
  # A velocidade y mínima para o robô em m/s 

  max_rot_vel : 1.6
  # O valor absoluto da velocidade rotacional máxima para o robô em rad/s 

  min_rot_vel : 0.6
  # O valor absoluto da velocidade rotacional mínima para o robô em rad/s 



### Parâmetros de tolerância da meta
  yaw_goal_tolerance : 0.05
  # A tolerância em radianos para o controlador em guinada/rotação ao atingir seu objetivo 

  xy_goal_tolerance : 0.1
  # A tolerância em metros para o controlador na distância x e y ao atingir uma meta 

  # latch_xy_goal_tolerance : false
  # Se a tolerância da meta estiver travada, se o robô chegar ao local xy da meta, ele simplesmente girará no lugar, mesmo que termine fora da tolerância da meta enquanto estiver fazendo isso. 



### Parâmetros de simulação de encaminhamento
  sim_time : 1.0
  # A quantidade de tempo para simular trajetórias em segundos 

  sim_granularity : 0.025
  # O tamanho do passo, em metros, a ser percorrido entre pontos em uma determinada trajetória 

  vx_samples : 20
  # O número de amostras a serem usadas ao explorar o espaço de velocidade x 

  #vy_samples : 0
  # O número de amostras a serem usadas ao explorar o espaço de velocidade y 

  vth_samples : 40
  # O número de amostras a serem usadas ao explorar o espaço de velocidade teta 


### Parâmetros de pontuação da trajetória
  path_distance_bias : 48
  # A ponderação de quanto o controlador deve ficar próximo ao caminho que lhe foi dado 

  goal_distance_bias : 88
  # A ponderação de quanto o controlador deve tentar atingir seu objetivo local, também controla a velocidade 

  occdist_scale : 0.05
  # A ponderação de quanto o controlador deve tentar evitar obstáculos 

  forward_point_distance : 0.325
  # A distância do ponto central do robô para colocar um ponto de pontuação adicional, em metros 

  stop_time_buffer : 0.2
  # A quantidade de tempo que o robô deve parar antes de uma colisão para que uma trajetória seja considerada válida em segundos 

  scaling_speed : 0.5
  # O valor absoluto da velocidade na qual começar a dimensionar a pegada do robô, em m/s 

  max_scaling_factor : 0.2
  # O fator máximo para dimensionar a pegada do robô por 



### Oscillation Prevention Parameters
  oscillation_reset_dist : 0.05
  # Qual a distância que o robô deve percorrer em metros antes que os sinalizadores de oscilação sejam redefinidos


## Parâmetros do Plano Global
  prune_plan : true
  # Define se deve ou não consumir o plano enquanto o robô se move ao longo do caminho. Se definido como verdadeiro, os pontos cairão no final do plano quando o robô passar 1 metro além deles. 
