allow_unknown: true
# Especifica se permite ou não que o planejador crie planos que percorram um espaço desconhecido.
# NOTA: se você estiver usando um mapa de custos costmap_2d em camadas com uma camada de voxel ou obstáculo,
# você também deve definir o parâmetro track_unknown_space para que essa camada seja verdadeira,
# ou converterá todo o seu espaço desconhecido em espaço livre (pelo qual o planejador passará alegremente).
# (bool, default: true)

default_tolerance: 0.0
# A tolerância no ponto de meta para o planejador. O planejador tentará criar um plano que seja o mais próximo possível
# a meta especificada possível, mas não além de default_tolerance.
# (duplo, padrão: 0.0)

visualize_potential: false
# Especifica se deseja ou não visualizar a área potencial calculada por meio de um PointCloud2.
# (bool, default: false)

use_dijkstra: true
# Se verdadeiro, use o algoritmo de dijkstra. Caso contrário, A*.
# (bool, default: true)

use_quadratic: true
# Se verdadeiro, use a aproximação quadrática do potencial. Caso contrário, use um cálculo mais simples.
# (bool, default: true)

use_grid_path: false
# Se verdadeiro, crie um caminho que siga os limites da grade. Caso contrário, use o método de gradiente descendente.
# (bool, default: false)

old_navfn_behavior: false
# Se, por algum motivo, você quiser que o global_planner espelhe exatamente o comportamento do navfn,
# defina isso como true (e use os padrões para os outros parâmetros booleanos)
# (bool, default: false)

lethal_cost: 253 
# Custo Letal (reconfiguração dinâmica) (int, padrão: 253)

neutral_cost: 50
# Custo Neutro (reconfiguração dinâmica) (int, default: 50)

cost_factor: 3.0
# Fator para multiplicar cada custo do mapa de custos por (reconfiguração dinâmica) (duplo, padrão: 3.)

publish_potential: true
# Publicar Mapa de Custo Potencial (reconfiguração dinâmica) (bool, padrão: True)

orientation_mode: 0
# Como definir a orientação de cada ponto
# (Nenhum=0, Forward=1, Interpolate=2, ForwardThenInterpolate=3, Backward=4, Leftward=5, Rightward=6) (reconfiguração dinâmica)
# (int, padrão: 0)

orientation_window_size: 1
# Qual janela usar para determinar a orientação com base na derivada de posição especificada pelo modo de orientação (reconfiguração dinâmica)
# (int, padrão: 1)
