# parâmetros geométricos do robô:

# Diâmetro de std. roda mecanum
wheelDiameter: 0.254
# Comprimento do robô móvel do centro da roda ao centro da roda
robotLength: 0.475
# Largura do centro da roda ao centro da roda
robotWidth: 0.548
#stddev vel x
devX: 0.447
#stddev vel y
devY: 0.447
#stddev vel z
devZ: 0.447
#stddev vel roll
devRoll: 0.447
#stddev vel pitch
devPitch: 0.447
#stddev vel x yaw
devYaw: 0.447