  base_frame : "base_link"

  map_frame  : "map"

  odom_frame : "odom"

  map_update_interval : 1.0
  # Quanto tempo (em segundos) entre as atualizações do mapa. A redução desse número atualiza a grade de ocupação com mais frequência, em detrimento de uma maior carga computacional.

  maxUrange : 28
  # O alcance máximo utilizável do laser. Um feixe é cortado para este valor.

  sigma : 0.05
  # O sigma usado pela correspondência de endpoint gananciosa

  kernelSize : 1
  # O kernel no qual procurar uma correspondência 

  lstep : 0.05
  # A etapa de otimização na tradução

  astep : 0.05
  # A etapa de otimização na rotação 

  iterations : 5
  # A etapa de otimização na rotação 

  lsigma : 0.075
  # O sigma de um feixe usado para cálculo de probabilidade

  ogain : 3.0
  # Ganho a ser usado ao avaliar a probabilidade, para suavizar os efeitos de reamostragem 

  lskip : 0
  # Número de feixes a serem ignorados em cada varredura. 

  minimumScore : 100.0
  # Pontuação mínima por considerar o resultado da verificação como bom. Pode evitar estimativas de poses saltitantes em grandes espaços abertos ao usar scanners a laser com alcance limitado (por exemplo, 5m). As pontuações vão até 600' #tente 50, por exemplo, ao enfrentar problemas de estimativa de salto. 

  srr : 0.25
  # Erro de odometria na tradução em função da tradução (rho/rho)

  srt : 0.5
  # Erro de odometria na translação em função da rotação (rho/theta) 

  str : 0.25
  # Erro de odometria na rotação em função da translação (teta/rho) 

  stt : 0.5
  # Erro de odometria na rotação em função da rotação (teta/teta)

  linearUpdate : 0.1
  # Processar uma varredura cada vez que o robô traduz até aqui 

  angularUpdate : 0.1
  # Processar uma varredura cada vez que o robô gira até aqui 

  temporalUpdate : 0.5
  # Processar uma verificação se a última verificação processada for anterior ao tempo de atualização em segundos. Um valor menor que zero desativará as atualizações baseadas em tempo. 

  resampleThreshold : 0.5
  # Limite de reamostragem baseado em Neff

  particles : 100
  # Número de partículas no filtro.

  xmin : -20.0
  #Tamanho inicial do mapa 

  ymin : -20.0
  #Tamanho inicial do mapa

  xmax : 20.0
  #Tamanho inicial do mapa 

  ymax : 20.0
  #Tamanho inicial do mapa 

  delta : 0.03
  # Resolução do mapa.

  #llsamplerange: 0,01
  # Intervalo de amostragem translacional para a probabilidade

  #llsamplestep : 0,01
  # Etapa de amostragem translacional para a probabilidade

  #lasamplerange : 0,005
  # Intervalo de amostragem angular para a probabilidade

  #lasamplestep : 0,005
  # Etapa de amostragem angular para a probabilidade

  transform_publish_period : 0.05
  # Quanto tempo (em segundos) entre as publicações de transformação.

  occ_thresh : 0.25
  # Limite nos valores de ocupação do gmapping. As células com maior ocupação são consideradas ocupadas (ou seja, definidas como 100 no sensor_msgs/LaserScan resultante). Novo em 1.1.0.

  #maxRange
  # O alcance máximo do sensor. Se as regiões sem obstáculos dentro do alcance do sensor devem aparecer como espaço livre no mapa, defina maxUrange < alcance máximo do sensor real <= maxRan


