EBandPlannerROS:

  costmap_weight : 5.0 # pesos para o custo do mapa de custo
  Ctrl_Rate : 10.0 # Hz
  differential_drive : false # true para robôs com rodas diferencial
  max_acceleration : 0.6 # m/s^2
  max_rotational_acceleration : 1.5 # rad/s^2
  max_vel_lin : 0.8 # m/s
  max_vel_th : 1.0 # rad/s
  min_vel_lin : 0.0 # m/s
  min_vel_th : 0.0 # rad/s
  xy_goal_tolerance : 0.1 # tolerância em metros para o controlador na distância x e y ao atingir uma meta
  yaw_goal_tolerance : 0.05 # tolerância em radianos para o controlador em guinada/rotação ao atingir seu objetivo
  rot_stopped_vel : 0.01 
  trans_stopped_vel : 0.01
  eband_min_relative_overlap : 0.7 
  eband_tiny_bubble_distance: 0.01 
  eband_tiny_bubble_expansion : 0.01  
  eband_internal_force_gain : 1.0  
  eband_external_force_gain : 2.0  
  num_iterations_eband_optimization : 3  
  eband_equilibrium_approx_max_recursion_depth : 4  
  eband_equilibrium_relative_overshoot : 0.75  
  eband_significant_force_lower_bound : 0.15   
  k_prop : 4.0 # parametro de controle proporcional
  k_damp : 3.5 # parametro de controle de amortecimento
  Ctrl_Rate : 10.0 # Hz
  virtual_mass : 0.75 # massa virtual em kg
  max_translational_acceleration : 0.5 # m/s^2
  rotation_correction_threshold : 0.5 # radianos 
  differential_drive : False # true para robôs com rodas diferencial
  bubble_velocity_multiplier : 2.0 # multiplicador de velocidade da bolha
  rotation_threshold_multiplier : 1.0 # multiplicador de limite de rotação  
  disallow_hysteresis : False # desabilita histerese





