#######PARÂMETRO GERAL DE FILTRO########

min_particles : 500
##### Número mínimo permitido de partículas (padrão: 100)

max_particles : 1250
##### Número máximo permitido de partículas (padrão: 5000)

kld_err : 0.01
##### Erro máximo entre a distribuição verdadeira e a distribuição estimada. 

kld_z : 0.99
##### Quantil normal padrão superior para (1 - p), onde p é a probabilidade de que o erro na distribuição estimada seja menor que kld_err.

update_min_d : 0.05
##### Movimento translacional necessário antes de realizar uma atualização de filtro. (padrão: 0,2)

update_min_a: 0.05
##### Movimento rotacional necessário antes de realizar uma atualização de filtro.

resample_interval : 2
##### Número de atualizações de filtro necessárias antes da reamostragem.

transform_tolerance : 0.1 
##### Tempo para a data posterior da transformação publicada, para indicar que essa transformação é válida no futuro. (padrão: 0,1)

#recovery_alpha_slow : 0.0001
##### Taxa de decaimento exponencial para o filtro de peso médio lento, usado para decidir quando recuperar adicionando poses aleatórias. Um bom valor pode ser 0,001. 

#recovery_alpha_fast : 0.1
##### Taxa de decaimento exponencial para o filtro de peso médio rápido, usado para decidir quando recuperar adicionando poses aleatórias. Um bom valor pode ser 0,1.

initial_pose_x : 0.0 
##### Média de pose inicial (x), usada para inicializar o filtro com distribuição gaussiana.

initial_pose_y : 0.0
##### Média da pose inicial (y), usada para inicializar o filtro com distribuição gaussiana. 

initial_pose_a : 0.0 
#### Média de pose inicial (guinada), usada para inicializar o filtro com distribuição gaussiana.

initial_cov_xx : 0.25
##### Covariância de pose inicial (x*x), usada para inicializar o filtro com distribuição gaussiana.

initial_cov_yy : 0.25
##### Covariância de pose inicial (y*y), usada para inicializar o filtro com distribuição gaussiana. 

initial_cov_aa : 0.1
##### Covariância de pose inicial (yaw*yaw), usada para inicializar o filtro com distribuição gaussiana.

gui_publish_rate : 2.0 
##### Taxa máxima (Hz) na qual varreduras e caminhos são publicados para visualização, -1,0 para desabilitar. 

save_pose_rate : 0.5
##### Taxa máxima (Hz) na qual armazenar a última pose e covariância estimadas para o servidor de parâmetros, nas variáveis ~initial_pose_* e ~initial_cov_*. Essa pose salva será usada em #####execuções subsequentes para inicializar o filtro. -1.0 para desabilitar. 

use_map_topic : true
##### Quando definido como true, o AMCL assinará o tópico do mapa em vez de fazer uma chamada de serviço para receber seu mapa. Novo na navegação 1.4.2 (padrão: falso)

first_map_only : false
##### Quando definido como verdadeiro, o AMCL usará apenas o primeiro mapa ao qual se inscrever, em vez de atualizar sempre que um novo for recebido. Novo na navegação 1.4.2 (padrão: falso)



#######LASER MODEL PARAMETERS#######

 
laser_min_range : -1.0
##### Faixa de varredura mínima a ser considerada; -1.0 fará com que o alcance mínimo relatado do laser seja usado.

laser_max_range : -1.0
##### Faixa máxima de varredura a ser considerada; -1.0 fará com que o alcance máximo relatado do laser seja usado. 

laser_max_beams : 200
##### Quantos feixes uniformemente espaçados em cada varredura devem ser usados ao atualizar o filtro. (Padrão: 30)

#laser_z_hit : 0.95
##### Peso da mistura para a parte z_hit do modelo. 

#laser_z_short : 0.1
##### Peso da mistura para a parte z_short do modelo. 

#laser_z_max : 0.05
##### Peso da mistura para a parte z_max do modelo. 

#laser_z_rand : 0.05
##### Peso da mistura para a parte z_rand do modelo. 

#laser_sigma_hit : 0.2 
##### Desvio padrão para o modelo gaussiano usado na parte z_hit do modelo. 

#laser_lambda_short : 0.1
##### Parâmetro de decaimento exponencial para a parte z_short do modelo. 

laser_likelihood_max_dist : 2.0 
##### Distância máxima para fazer a inflação de obstáculos no mapa, para uso no modelo verossimilhança_campo. 

laser_model_type : "likelihood_field"
##### Qual modelo usar, feixe, campo_verossimilhança ou campo_verossimilhança_prob (o mesmo que campo_verossimilhança, mas incorpora o recurso beamskip, se ativado).


#######PARÂMETROS DO MODELO DE ODOMETRIA####### 

odom_model_type : omni-corrected
##### Qual modelo usar, "diff", "omni", "diff corrigido" ou "omni-corrigido". 

odom_alpha1 : 0.05
##### Especifica o ruído esperado na estimativa de rotação da odometria do componente rotacional do movimento do robô. 

odom_alpha2 : 0.05
##### Especifica o ruído esperado na estimativa de rotação da odometria do componente translacional do movimento do robô. 

odom_alpha3 : 0.05
##### Especifica o ruído esperado na estimativa de translação da odometria do componente translacional do movimento do robô. 

odom_alpha4 : 0.05
##### Especifica o ruído esperado na estimativa de translação da odometria do componente rotacional do movimento do robô. 

odom_alpha5 : 0.05
##### Parâmetro de ruído relacionado à tradução (usado apenas se o modelo for "omni"). 

odom_frame_id : "odom"
##### Qual armação usar para odometria. 

base_frame_id : "base_link"
##### Qual estrutura usar para a base do robô 

global_frame_id : "map"
##### O nome do quadro de coordenadas publicado pelo sistema de localização 

tf_broadcast : true
##### Defina como false para evitar que o amcl publique a transformação entre o quadro global e o quadro de odometria. 

